### PR TITLE
C++ Recoil Control System & Read memory using system call.

### PR DESCRIPTION
**Pull request by RutOf**
- Added a descriptive error message to the strings returned in case of errors, to make debugging easier.
- Moved the timing check after the initialization of the state, to avoid including the initialization time in the elapsed time.
- Changed the elapsed time check to use the count() method instead of the milliseconds() method, for better performance.
- Added a system call to read the memory address, assuming a read_memory() function exists for this purpose, and checking for errors in case the function call fails.
- Changed the return value of the function to the value read from the memory address, instead of returning a fixed success string.

It is worth noting that the **read_memory**() function used here is assumed to exist and may not be standard C++ functionality. Similarly, the ntusrinit() function used in the original code may also not be standard C++ functionality.

- Added a macro **MINIMUM_CAPACITY** to define the minimum capacity of the list.
- Changed the condition for reducing the capacity of the list. Now, the capacity will be reduced if it is greater than **MINIMUM_CAPACITY** and the new size of the list is less than or equal to half of the capacity.
- Added code to calculate the new capacity of the list, which is half of the current capacity or **MINIMUM_CAPACITY**, whichever is greater.
- Reallocated the memory for the list with the new capacity and updated the capacity of the list accordingly.

### CODE REVIEW

**Comment by RutOf** [comment]
You can verify correctness and make further corrections here.

**Review by Serups — COMMENTED** [review]
```cpp
// Check if we can reduce the capacity of g_hooks
if (g_hooks.capacity > MINIMUM_CAPACITY && g_hooks.size <= g_hooks.capacity / 2 && g_hooks.capacity / 2 >= INITIAL_HOOK_CAPACITY) {
  // Reduce the capacity of g_hooks
  g_hooks.capacity /= 2;
}

```

**Review by Serups — COMMENTED** [review]
```cpp
return "Error: Failed to initialize ntusr. Please check that the required files are present and try again.";
```

**Review by Serups — COMMENTED** [review]
```cpp
Vector3 controlRotation = read<Vector3>(PlayerController + Offsets::ControlRotation);
Vector3 deltaRotation = (cameraRotation - controlRotation).normalize();
cameraRotation = target - deltaRotation * smoothFactor;
cameraRotation = cameraRotation.smooth(controlRotation, smoothFactor).clamp();
write<Vector3>(PlayerController + Offsets::ControlRotation, cameraRotation.toD3DXVECTOR3());

```

**Comment by Serups** [comment]
Here's how it all works. that has been shortened and has the same efficiency

**Comment by Serups** [comment]
```cpp
	void c_renderer::draw_rect(float x, float y, float width, float height, D3DCOLOR col) {
		D3DXVECTOR2 points[5];
		std::string str("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		setup point[4] (!091.x20) = (("gtav.exe"))
```

**Pull request merged**
